spring:
  config:
    activate:
      on-profile: docker
  threads:
    virtual:
      enabled: true
  datasource:

    url: jdbc:postgresql://db:5432/${DB_NAME:handrilldb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
app:
  cors:
    allowed-origins:
      - http://localhost
      - http://frontend
